app/territory_sectors/flat/urls.py
from django.urls import path
from .views import FlatListView, FlatCreateView, FlatUpdateView, FlatDeleteView

urlpatterns = [
    path('', FlatListView.as_view(), name='flat_list'),
    path('create/', FlatCreateView.as_view(), name='flat_add'),
    path('<int:pk>/', FlatUpdateView.as_view(), name='flat_update'),
    path('<int:pk>/delete/', FlatDeleteView.as_view(), name='flat_delete'),
]

app/territory_sectors/house/urls.py
from django.urls import path
from .views import HouseListView, HouseCreateView, HouseUpdateView, \
    HouseDeleteView

urlpatterns = [
    path('', HouseListView.as_view(), name='house_list'),
    path('create/', HouseCreateView.as_view(), name='house_add'),
    path('<int:pk>/', HouseUpdateView.as_view(), name='house_update'),
    path('<int:pk>/delete/', HouseDeleteView.as_view(), name='house_delete'),
]

app/territory_sectors/issue/urls.py
from django.urls import path
from .views import IssueListView, IssueCreateView, IssueDetailView, \
    CommentCreateView

urlpatterns = [
    path('', IssueListView.as_view(), name='issue_list'),
    path('create/', IssueCreateView.as_view(), name='issue_add'),
    path('<int:pk>/', IssueDetailView.as_view(), name='issue_detail'),
    path('comment/<int:pk>', CommentCreateView.as_view(),
         name='comment_create'),
]

app/territory_sectors/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexView, UserLoginView, UserLogoutView, UUIDView, StatView
from django.conf import settings
from django.conf.urls.static import static

# import shortuuid

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='root'),
    path('stat/', StatView.as_view(), name='stat'),
    path('<str:pk>', UUIDView.as_view(), name='uuid'),
    path('login/', UserLoginView.as_view(), name='user_login'),
    path('logout/', UserLogoutView.as_view(), name='user_logout'),
    path('flat/', include('territory_sectors.flat.urls')),
    path('house/', include('territory_sectors.house.urls')),
    path('sector/', include('territory_sectors.sector.urls')),
    path('uuid/', include('territory_sectors.uuid_qr.urls')),
    path('issue/', include('territory_sectors.issue.urls')),
]
if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/territory_sectors/flat/models.py
from django.db import models

from territory_sectors.house.models import House
from territory_sectors.language.models import Language
from territory_sectors.uuid_qr.models import Uuid
from simple_history.models import HistoricalRecords


class StatManager(models.Manager):
    def total_count(self):
        return self.count()

    def total_ru_count(self):
        return self.filter(language__id=1).count()


class Flat(models.Model):
    date_joined = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    house = models.ForeignKey(to=House, on_delete=models.CASCADE)
    number = models.CharField(max_length=300, null=True, blank=True)
    entrance = models.IntegerField(null=True, blank=True)
    floor = models.IntegerField(null=True, blank=True)
    way_desc = models.CharField(max_length=1500)
    language = models.ForeignKey(to=Language, on_delete=models.SET_DEFAULT,
                                 default=1)
    uuid = models.OneToOneField(to=Uuid, null=True, blank=True,
                                on_delete=models.SET_NULL)
    history = HistoricalRecords()
    objects = models.Manager()
    stat = StatManager()

    class Meta:
        ordering = ['house', 'entrance', 'floor', 'number']

    def __str__(self):
        return f'{self.house.address}(' \
               f'{self.entrance}-{self.floor}-{self.number})'

app/territory_sectors/flat/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import FlatForm
from .mixins import HousesAddMixin, SeveralInstanceCreateMixin
from .models import Flat
from django.utils.translation import gettext_lazy as _

from ..mixins import LoginRequiredMixinCustom


class FlatCreateView(LoginRequiredMixinCustom, SeveralInstanceCreateMixin,
                     SuccessMessageMixin, CreateView):
    form_class = FlatForm
    template_name = "flat/create.html"
    success_url = reverse_lazy('flat_list')
    login_url = reverse_lazy("user_login")
    extra_context = {
        'header': _('Create flat'),
        'button_title': _('Create'),
    }
    success_message = _('Flat created successfully')


class FlatListView(LoginRequiredMixinCustom, HousesAddMixin, ListView):
    model = Flat
    template_name = "flat/list.html"
    extra_context = {
        "remove_title": _("remove")
    }


class FlatUpdateView(LoginRequiredMixinCustom,
                     SuccessMessageMixin, UpdateView):
    model = Flat
    form_class = FlatForm
    template_name = "flat/create.html"
    success_url = reverse_lazy('flat_list')
    extra_context = {
        'header': _('Update Flat'),
        'button_title': _('Update'),
    }
    success_message = _('Flat updated successfully')


class FlatDeleteView(LoginRequiredMixinCustom,
                     SuccessMessageMixin, DeleteView):
    model = Flat
    template_name = "flat/delete.html"
    success_url = reverse_lazy('flat_list')
    extra_context = {
        'header': _('Remove flat'),
        'button_title': _('Remove '),
        'message': _('Are you sure delete flat '),
    }
    success_message = _('Flat deleted successfully')

app/territory_sectors/house/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django_filters.views import FilterView

from .filters import AddressFilter
from .forms import HouseForm
from .mixins import CountFlatsMixin, ImageResizeBeforeMixin
from .models import House
from django.utils.translation import gettext_lazy as _
from ..mixins import LoginRequiredMixinCustom


class HouseCreateView(LoginRequiredMixinCustom, ImageResizeBeforeMixin,
                      SuccessMessageMixin, CreateView):
    form_class = HouseForm
    template_name = "house/create.html"
    success_url = reverse_lazy('house_list')
    extra_context = {
        'header': _('Create house'),
        'button_title': _('Create'),
        'langs': House.get_lang_list_qs(),
    }
    success_message = _('House created successfully')


class HouseUpdateView(LoginRequiredMixinCustom, ImageResizeBeforeMixin,
                      SuccessMessageMixin, UpdateView):
    model = House
    form_class = HouseForm
    template_name = "house/create.html"
    success_url = reverse_lazy('house_list')
    extra_context = {
        'header': _('Update house'),
        'button_title': _('Update'),
        'langs': House.get_lang_list_qs(),
    }
    success_message = _('House updated successfully')


class HouseListView(LoginRequiredMixinCustom, CountFlatsMixin, FilterView,
                    ListView):
    filterset_class = AddressFilter
    model = House
    template_name = "house/list.html"
    extra_context = {
        'remove_title': _('Remove'),
        'select': _('Select')
    }
    ordering = 'address'


class HouseDeleteView(LoginRequiredMixinCustom,
                      SuccessMessageMixin, DeleteView):
    model = House
    template_name = "house/delete.html"
    success_url = reverse_lazy('house_list')
    extra_context = {
        'header': _('Remove house'),
        'button_title': _('Remove '),
        'message': _('Are you sure delete house '),
    }
    success_message = _('House deleted successfully')

app/territory_sectors/issue/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Count
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView
from django.utils.translation import gettext_lazy as _

from .forms import IssueForm, CommentForm
from ..mixins import SetAuthorMixin, LoginRequiredMixinCustom
from .models import Issue, Comment


class IssueCreateView(LoginRequiredMixinCustom, SetAuthorMixin,
                      SuccessMessageMixin, CreateView):
    form_class = IssueForm
    template_name = "issue/create.html"
    success_url = reverse_lazy("issue_list")
    login_url = reverse_lazy("user_login")
    extra_context = {
        'header': _('Create issue'),
        'button_title': _('Create'),
    }
    success_message = _('Issue created successfully')


class IssueListView(LoginRequiredMixinCustom, ListView):
    model = Issue
    template_name = "issue/list.html"
    extra_context = {
        'header': _('List issues'),
    }

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.annotate(comments_count=Count('comment'))
        return qs

# class CommentCreateView(CreateView):
#     model = Comment
#     form_class = CommentForm
#     template_name = 'comment_form.html'
#     success_url = reverse_lazy('home')
#
#     def form_valid(self, form):
#         form.instance.issue_id = self.kwargs['pk']
#         return super().form_valid(form)
#


class IssueDetailView(LoginRequiredMixinCustom, SetAuthorMixin, DetailView):
    model = Issue
    template_name = "issue/detail.html"
    extra_context = {
        'header': _('Issue detail'),
        'button_title': _('Comment'),
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = Comment.objects.filter(issue_id=context['issue'])
        context['new_comment'] = CommentForm()
        return context


class CommentCreateView(SuccessMessageMixin, CreateView):
    success_message = _("Issue updated")
    model = Comment
    form_class = CommentForm
    template_name = 'issue/comment_form.html'
    success_url = reverse_lazy('issue_list')

    def form_valid(self, form):
        form.instance.issue_id = self.kwargs['pk']
        form.instance.author_id = self.request.user.id
        issue = Issue.objects.get(pk=form.instance.issue_id)
        issue.completed = form.cleaned_data['completed']
        issue.save()
        # logging.error(form.cleaned_data)
        return super().form_valid(form)

app/territory_sectors/sector/views.py
from django.contrib.gis.db.models.functions import AsGeoJSON
from django.contrib.messages.views import SuccessMessageMixin
from django.http import JsonResponse
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .forms import SectorForm
from .models import Sector
from django.utils.translation import gettext_lazy as _
from .mixins import GeoJSONAnnotateMixin, ContextAllHousesIntoMixin, \
    CentroidAnnotateMixin, NatSortMixin
from ..mixins import LoginRequiredMixinCustom
from django.views import View


class SectorCreateView(LoginRequiredMixinCustom, ContextAllHousesIntoMixin,
                       SuccessMessageMixin, CreateView):
    model = Sector
    form_class = SectorForm
    template_name = "sector/create.html"
    success_url = reverse_lazy('sector_list')
    extra_context = {
        'header': _('Create sector'),
        'button_title': _('Create'),
        'sectors': model.objects.all().annotate(
            geojson=AsGeoJSON('contour'),
        )
    }
    success_message = _('Sector created successfully')

    def form_valid(self, form):
        sector = form.save(commit=False)
        sector.assign_uuid()
        return super().form_valid(form)


class SectorUpdateView(LoginRequiredMixinCustom, CentroidAnnotateMixin,
                       ContextAllHousesIntoMixin, GeoJSONAnnotateMixin,
                       SuccessMessageMixin, UpdateView):
    model = Sector
    form_class = SectorForm
    template_name = "sector/create.html"
    success_url = reverse_lazy('sector_list')
    extra_context = {
        'header': _('Update Sector'),
        'button_title': _('Update'),
        'sectors': model.objects.all().annotate(
            geojson=AsGeoJSON('contour')
        )
    }
    success_message = _('Sector updated successfully')

    # def get_context_data(self, **kwargs):
    #     """Add context."""
    #     context = super().get_context_data(**kwargs)
    #     url = self.request.build_absolute_uri(
    #         self.object.get_absolute_url(
    #             reverse("uuid", kwargs={'pk': self.object.uuid_id})
    #         )
    #     )
    #     img = make(url)
    #
    #     buffer = BytesIO()
    #     img.save(buffer)
    #     buffer.seek(0)
    #
    #     file_size = len(buffer.getvalue())
    #     file_name = f"qr_{self.id}.png"
    #     file_content = ContentFile(buffer.read(), name=file_name)
    #     img_data = base64.b64encode(
    #         InMemoryUploadedFile(
    #             file_content, None, file_name, 'image/png', file_size, None
    #         ).read()
    #     ).decode('utf-8')
    #
    #     context['qr_img_data'] = img_data
    #     return context


class SectorPrintView(LoginRequiredMixinCustom,
                      CentroidAnnotateMixin, UpdateView):
    model = Sector
    fields = ['name', 'uuid']
    template_name = "sector/print_sector_quadra.html"
    success_url = reverse_lazy('sector_list')
    extra_context = {
        'print_header': _('Sector '),
        'additional_rows': "*" * 2,
    }

    def get_context_data(self, **kwargs):
        """Add context."""
        context = super().get_context_data(**kwargs)
        context['url'] = self.request.build_absolute_uri(
            reverse_lazy(
                "uuid", kwargs={'pk': self.object.uuid_id})
        )
        if self.object.for_search:
            context['additional_rows'] = "*"*40
        return context


class SectorListView(LoginRequiredMixinCustom, NatSortMixin,
                     ContextAllHousesIntoMixin, GeoJSONAnnotateMixin,
                     CentroidAnnotateMixin, ListView):
    model = Sector
    template_name = "sector/list.html"
    extra_context = {
        'remove_title': _('remove'),
    }
    # ordering = 'name',

    def get_queryset(self):
        qs = super().get_queryset()

        status = self.extra_context.get('status', False)
        if status == 'for-serve':
            return qs.filter(for_search=False)
        elif status == 'for-search':
            return qs.filter(for_search=True)

        return qs


class SectorStatusHistory(LoginRequiredMixinCustom, ListView):
    model = Sector
    template_name = 'sector/history_status.html'
    extra_context = {
        'header': _('History statuses of '),
    }

    def get_queryset(self):
        sector_id = self.kwargs['pk']
        sector = Sector.objects.get(id=sector_id)
        history = sector.history.all().order_by(
            'history_date')
        records = [history[0]]
        for record in history:
            delta = record.diff_against(records[-1])
            if any(
                    (field in delta.changed_fields for field in
                     ('status', 'assigned_to')
                     )
            ):
                records.append(record)
        return records[::-1]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs['pk']
        context['sector_name'] = self.model.objects.get(pk=pk).name
        return context


class SectorDeleteView(LoginRequiredMixinCustom, GeoJSONAnnotateMixin,
                       CentroidAnnotateMixin, SuccessMessageMixin, DeleteView):
    model = Sector
    template_name = "sector/delete.html"
    success_url = reverse_lazy('sector_list')
    extra_context = {
        'header': _('Remove sector'),
        'button_title': _('Remove '),
        'message': _('Are you sure delete sector '),
    }
    success_message = _('Sector deleted successfully')


class SectorCheckInOutView(LoginRequiredMixinCustom, View):
    def post(self, request, *args, **kwargs):
        sector_id = self.kwargs.get('pk')
        data = request.body.decode()
        # sector = Sector.objects.get(id=sector_id)
        # sector.status
        # sector.save()

        # Return a JSON response with a success message
        return JsonResponse(
            {'message': f'Marker {sector_id} updated successfully.\n {data=}'})
    # model = Sector
    # form_class = SectorForm
    # template_name = "sector/checkinout.html"
    # success_url = reverse_lazy('sector_list')
    # extra_context = {
    #     'sectors': model.objects.all().annotate(
    #         geojson=AsGeoJSON('contour')
    #     )
    # }
    # success_message = _('Sector updated successfully')

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     # raise IOError(self.object.status.name)
    #     if self.object.status.name == 'assigned':
    #         context['header'] = _('Check out sector'),
    #         context['button_title'] = _('Check out'),
    #     if self.object.status.name in ('free', 'completed'):
    #         context['header'] = _('Check in sector'),
    #         context['button_title'] = _('Check in'),
    #     if self.object.status.name == 'under_construction':
    #         context['header'] = _(
    #         '<p style="color:red">Sector in service mode.Pay attention</p>'),
    #     return context
    #
    # def get_success_message(self, cleaned_data):
    #     return cleaned_data
    #     # if self.object.status.name == 'assigned':
    #     #     return _("Sector successfully checked out")
    #     # elif self.object.status.name in ('free', 'completed'):
    #     #     return _("Sector successfully checked in to ")

app/territory_sectors/templates/house/bulk_flat_create_update.html
{% load i18n %}
{% load bootstrap4 %}
{% load static %}
<script src="{% static "house.js" %}"></script>

<div class="form-row" ><h2> Flats</h2></div>
<div id="flat_table" class="form-row" style="visibility: hidden">
    <div class="form-row my-2" id="flat_template" style="visibility: hidden">
        <div class="col-md-2" id="entrance_">
            <input type="text" placeholder=" " class="form-control">
             <label class="form-control-placeholder">{% trans "entrance" %}</label>
        </div>
        <div class="col-md-2" id="number_">
            <input type="text" placeholder=" " class="form-control">
            <label class="small form-control-placeholder">{% trans "number(',' is delimiter)" %}</label>
        </div>
        <div class="col-md-2" id="floor_">
            <input type="text"  placeholder=" " class="form-control">
            <label class="form-control-placeholder">{% trans "floor" %}</label>
        </div>
        <div class="col-auto" id="way_desc_">
            <textarea cols="30" rows="1" class="form-control" placeholder=" "> </textarea>
            <label class="form-control-placeholder">{% trans "way_desc" %}</label>
        </div>
        <div class="col-md-2" id="language_">
            <select class ="form-control">
                {% for lang in langs %}
                    <option value="{{ lang.id }}">{{ lang.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col" id="remove">
            <button type="button" class="btn btn-outline-danger"  onclick="removeRow(this)">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"></path>
                  <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"></path>
                </svg>
          </button>
        </div>
    </div>
</div>
<script>
    fillFlats()

    const form = document.querySelector("#houseform");
    form.addEventListener("submit", function (){update_flats_data()});
</script>
<a href="#" title="add row" onclick="addRow();return false;">Add flat</a>

app/territory_sectors/templates/house/create.html
{% extends "base.html" %}
{% load i18n %}
{% load bootstrap4 %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static "sector.css" %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/autosize.js/4.0.2/autosize.min.js"></script>
{% endblock %}
{% block page_content %}
    <form method="post" action="." id="houseform" enctype="multipart/form-data">
    {% csrf_token %}
    <div class = "form">
      <h1 class="my-4"> {{ header }}</h1>
        {% for field in form %}
            {% if field.name == 'image_preview' %}
                {% if field.value %}
                  <a href="#" class="pop_modal"><img src="{{ field.value.url }}"></a>
                {% endif %}
            {% else %}
                {% if field.name == 'image' %}
                  {% if field.value %}
                    <div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
                      <div class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-body">
                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                            <img src="{{ field.value.url }}" class="imagepreview" style="width: 100%;" >
                          </div>
                        </div>
                      </div>
                    </div>
                   <script type="text/javascript">
                    $(function() {
                            $('.pop_modal').on('click', function() {
                                $('#imagemodal').modal('show');
                            });
                    });
                   </script>
                  {% endif %}
                {% endif %}
            {% bootstrap_field field %}
            {% endif %}
        {% endfor %}
        <div>
            {% include "house/bulk_flat_create_update.html" %}
        </div>
        <div class = "form-group">
            {% bootstrap_button button_title button_type="submit" button_class="mt-3 btn btn-primary" %}
        </div>
    </div>

    <input type="hidden" id="id" value="{{ house.id|default:'0' }}">
    </form>
{#    {% debug %}#}
{% endblock %}

{% block markers %}
    {% if object %}
        $(document).ready(function() {
          $('.form-control').each(function() {
            autosize(this);
          });
        });
        set_popup({{ house.id }}, "{{ house.address }}")
        set_marker({{ house.id }}, {{ house.gps_pos }});
        map_fly({{ house.gps_pos }});
    {% endif %}
    map.on('click', move_marker);
{% endblock %}

app/territory_sectors/templates/house/delete.html
{% extends "base.html" %}
{% load i18n %}
{% load bootstrap4 %}
{% block page_content %}
    <h1 class="my-4"> {{ header }}</h1>
    <form method="post" action=".">
    {% csrf_token %}
        <p>{{ message }} "{{ object.address }}"  ?</p>
{% bootstrap_button button_title button_type="submit" button_class="btn btn-danger" %}    </form>
{% endblock %}
{% block markers %}
        set_popup({{ house.id }}, "{{ house.address }}")
        set_marker({{ house.id }}, {{ house.gps_pos }});
{% endblock %}

app/territory_sectors/templates/house/filter.html
<div class = "card mb-3">
    {% load bootstrap4 %}
    <div class = "container my-3">
       <form method="get">
           {% for field in filter.form %}
           <div class="form-group">
                {% bootstrap_field field %}
           </div>
           {% endfor %}
           <div class="form-group">
                 {% bootstrap_button select button_type="submit" button_class="mt-3 btn btn-primary" %}
           </div>
       </form>
    </div>
</div>

app/territory_sectors/templates/house/list_flat.html
{% load i18n %}
{% load bootstrap4 %}
{% if house.flat_set.all %}
    <div class="card-body">
      <table class = "table table-striped">
        <tr>
            <th>{% translate "entrance" %}</th>
            <th>{% translate "number" %}</th>
            <th>{% translate "floor" %}</th>
            <th>{% translate "language" %}</th>
            <th>{% translate "way desc" %}</th>
            <th></th>
        </tr>
        {% for flat in house.flat_set.all %}
            <tr>
                <td> {{flat.entrance}}</td>
                <td> {{flat.number}} </td>
                <td> {{flat.floor}}</td>
                <td> {{flat.language}}</td>
                <td> {{ flat.way_desc }}</td>
                <td>
                    <form method="get" action="{% url "flat_delete" flat.id %}">
                        <button class="btn btn-outline-danger" button_type="submit" >
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                              <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"></path>
                              <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"></path>
                            </svg>
                        </button>
                    </form>
                </td>
            </tr>
        {% endfor %}
      </table>
    </div>
{% endif %}

app/territory_sectors/templates/house/pagination.html
<div>
<ul class="pagination justify-content-center" >
    {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1">1</a></li>
        {% if page_obj.number != 1 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>
        {% endif %}
    {% endif %}
        <li class="page-item active">
            <span class="page-link">{{ page_obj.number }}</span>
        </li>
    {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
        {% if page_obj.number != page_obj.paginator.num_pages %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
            </li>
        {% endif %}

    {% endif %}
{##}
{##}
{#            <a href="?page={{ page_obj.next_page_number }}">&raquo;</a>#}
{#            <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>#}
{#        {% endif %}#}
{#    </li>#}
</ul>
</div>